[package]
name = "mpris-discord-rpc"
version = "0.1.0"
edition = "2021"

[dependencies]
discord-rich-presence = "0.2.3"
mpris = "2.0.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
url-escape = "0.1.1"
serde_json = "1.0.111"
cacache = "12.0.0"
clap = { version = "4.4.18", features = ["derive"] }
dotenvy_macro = "0.15.7"

[profile.release]
strip = true
# optimizations for file size:
codegen-units = 1
panic = "abort"
