[package]
name = "mpris-discord-rpc"
version = "0.1.4"
edition = "2021"

[dependencies]
discord-rich-presence = { git = "https://github.com/vionya/discord-rich-presence.git", version = "0.2.4" }
mpris = "2.0.1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
url-escape = "0.1.1"
serde_json = "1.0.111"
clap = { version = "4.4.18", features = ["derive"] }
dotenvy_macro = "0.15.7"
pickledb = "0.5.1"

[profile.release]
strip = true
# optimizations for file size:
codegen-units = 1
panic = "abort"
