name: release

on:
  push:
    tags:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
    - name: Install Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt install libdbus-1-dev pkg-config
    - name: 'Create env file'
      run: |
        touch .env
        echo LASTFM_API_KEY=${{ secrets.LASTFM_API_KEY }} >> .env
    - name: Build
      run: |
        cargo build --release
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/release/mpris-discord-rpc

